# Dados de conexão com o seu Postgres
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=gabriel
quarkus.datasource.password=12345
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/ortiz_fitness

# Faz o Hibernate criar as tabelas do banco automaticamente baseado no seu código Java
quarkus.hibernate-orm.database.generation=update

# Ativa o log do SQL no console (bom para ver o que está acontecendo no banco)
quarkus.hibernate-orm.log.sql=true

quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:5500,http://127.0.0.1:5500
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=Content-Type,Authorization

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true

%dev.quarkus.hibernate-orm.dev-ui.allow-hql=true
